[package]
name = "zlide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = "0.3.69"
image = "0.25.1"
rand = "0.9.0-alpha.1"